name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - '**'
      -
jobs:

  # The Vault-repository is not actually private, but we clone it as if it was (without a GitHub token since it's public)

  testPrivateAction:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Checkout vault-action
        uses: actions/checkout@v3
        with:
          repository: jeroenmanders/vault-action
          ref: dev
          path: vault-action

      - name: Run docker-compose
        run: docker-compose up -d vault

      - name: Write some secrets
        run: |-
          docker run --network vault-action-test_default -e VAULT_ADDR="http://vault:8200"  --entrypoint "" --rm -e VAULT_TOKEN="testtoken" vault:latest vault secrets enable -version=1 -path my-secret kv 
          docker run --network vault-action-test_default -e VAULT_ADDR="http://vault:8200"  --entrypoint "" --rm -e VAULT_TOKEN="testtoken" vault:latest vault write my-secret/test altSecret=altValue field2=value2 field3=value3
          docker run --network vault-action-test_default -e VAULT_ADDR="http://vault:8200"  --entrypoint "" --rm -e VAULT_TOKEN="testtoken" vault:latest vault write my-secret/nested/test otherAltSecret=otherAltSecretValue

      - name: Test Vault Action (default KV V1)
        id: kv-secrets
        uses: ./vault-action
        with:
          url: http://localhost:8200
          token: testtoken
          secrets: |
            my-secret/test altSecret ;
            my-secret/test altSecret | NAMED_ALTSECRET ;
            my-secret/nested/test otherAltSecret ;
          skipMasks: otherAltSecret,blabla

      - name: Test Vault wildcard Action (default KV V1)
        id: kv-wildcard-secrets
        uses: ./vault-action
        with:
          url: http://localhost:8200
          token: testtoken
          secrets: |
            my-secret/test * | pre_;
          skipMasks: pre_altSecret,pre_field3

      - name: Print Vault Action Outputs
        run: |-
          echo "otherAltSecret: ${{ steps.kv-secrets.outputs.otherAltSecret }}"
          echo "NAMED_ALTSECRET: ${{ steps.kv-secrets.outputs.NAMED_ALTSECRET }}"
          echo "altSecret: ${{ steps.kv-secrets.outputs.altSecret }}"
          
          echo "--- Wildcard secrets: ----"
          echo "ALTSECRET: ${{ steps.kv-wildcard-secrets.outputs.pre_altsecret }}"
          echo "FIELD2: ${{ steps.kv-wildcard-secrets.outputs.pre_field2 }}"
          echo "FIELD3: ${{ steps.kv-wildcard-secrets.outputs.pre_field3 }}"
