name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - '**'
      -
jobs:

  # The Vault-repository is not actually private, but we clone it as if it was (without a GitHub token since it's public)

  integrationOSS:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Checkout vault-action
        uses: actions/checkout@v3
        with:
          repository: jeroenmanders/vault-action
          ref: dev
          path: vault-action

      - name: Run docker-compose
        run: docker-compose up -d vault

      - name: Write some secrets
        run: |-
          docker run --network vault-action-test_default -e VAULT_ADDR="http://vault:8200"  --entrypoint "" --rm -e VAULT_TOKEN="testtoken" vault:latest vault secrets enable -version=1 -path test-backend kv 
          docker run --network vault-action-test_default -e VAULT_ADDR="http://vault:8200"  --entrypoint "" --rm -e VAULT_TOKEN="testtoken" vault:latest vault write test-backend/data/test key=value 
          docker run --network vault-action-test_default -e VAULT_ADDR="http://vault:8200"  --entrypoint "" --rm -e VAULT_TOKEN="testtoken" vault:latest vault write test-backend/data/nested/test key2=value2

      - name: Test Vault Action (default KV V2)
        uses: ./vault-action/.github/actions/vault
        id: kv-secrets
        with:
          url: http://localhost:8200
          token: testtoken
          secrets: |
            test-backend/data/test secret ;
            test-backend/data/test secret | NAMED_SECRET ;
            test-backend/data/nested/test otherSecret ;

      - name: Test Vault Action (default KV V1)
        uses: ./vault-action/.github/actions/vault
        with:
          url: http://localhost:8200
          token: testtoken
          secrets: |
            my-secret/test altSecret ;
            my-secret/test altSecret | NAMED_ALTSECRET ;
            my-secret/nested/test otherAltSecret ;

      - name: Test Vault Action (cubbyhole)
        uses: ./vault-action/.github/actions/vault
        with:
          url: http://localhost:8200
          token: testtoken
          secrets: |
            /cubbyhole/test foo ;
            /cubbyhole/test zip | NAMED_CUBBYSECRET ;

      - name: Print Vault Action Outputs
        run: |-
          echo "otherSecret: $OTHER_SECRET_OUTPUT"
        env:
          OTHER_SECRET_OUTPUT: ${{ steps.kv-secrets.outputs.otherSecret }}
