name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - '**'
      -
jobs:

  # The Vault-repository is not actually private, but we clone it as if it was (without a GitHub token since it's public)

  integrationOSS:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Checkout vault-action
        uses: actions/checkout@v3
        with:
          repository: jeroenmanders/vault-action
          ref: dev
          path: vault-action

      - name: Run docker-compose
        run: docker-compose up -d vault

      - name: Write some secrets
        run: |-
          docker run --network vault-action-test_default -e VAULT_ADDR="http://vault:8200"  --entrypoint "" --rm -e VAULT_TOKEN="testtoken" vault:latest vault secrets enable -version=1 -path my-secret kv 
          docker run --network vault-action-test_default -e VAULT_ADDR="http://vault:8200"  --entrypoint "" --rm -e VAULT_TOKEN="testtoken" vault:latest vault write my-secret/test altSecret=altValue
          docker run --network vault-action-test_default -e VAULT_ADDR="http://vault:8200"  --entrypoint "" --rm -e VAULT_TOKEN="testtoken" vault:latest vault write my-secret/nested/test otherAltSecret=altValue

      - name: Test Vault Action (default KV V1)
        id: kv-secrets
        uses: ./vault-action/.github/actions/vault
        with:
          url: http://localhost:8200
          token: testtoken
          secrets: |
            my-secret/test altSecret ;
            my-secret/test altSecret | NAMED_ALTSECRET ;
            my-secret/nested/test otherAltSecret ;

      - name: Print Vault Action Outputs
        run: |-
          echo "s1: ${{ env.OTHER_SECRET_OUTPUT }}"
          echo "s2: ${{ steps.kv-secrets.outputs.NAMED_ALTSECRET }}"
          echo "s3: ${{ steps.kv-secrets.outputs.altSecret }}"
        env:
          OTHER_SECRET_OUTPUT: ${{ steps.kv-secrets.outputs.NAMED_ALTSECRET }}
